spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orclpdb
    username: local_db
    password: jordan1993
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  kafka:
    admin:
     auto-create: false
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max.request.size: 300000000
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      max-poll-records: 50 # Reduced from 100
      fetch-max-wait: 500ms
      fetch-min-size: 1MB
      properties:
        fetch.max.bytes: 300000000
        max.partition.fetch.bytes: 300000000
    listener:
      ack-mode: record
      missing-topics-fatal: false
      concurrency: 2
    retry:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, redis
  endpoint:
    health:
      show-details: always
    redis:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      all: true
      jvm: true
      http: true
      kafka: true
  security:
    enabled: false 
server:
  port: 8080
  max-http-header-size: 10MB
