spring:
 application:
  name: real-time-notification-service
 cloud:
  config:
   enabled: true
 profiles:
  active: dev
 data:
  redis:
   host: localhost #redis-container
   port: 6379

url:
 app:
  jwtCookieName: notification
  jwtSecret: realtimenotificationservice32byt
  jwtExpirationMs: 3600000
  
springdoc:
 api-docs:
  enabled: true
 swagger-ui:
  enabled: true